repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version or the version you need
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1  # Use the latest version or the version you need
    hooks:
      - id: bandit
        args: 
          - "-c"
          - "pyproject.toml"
          - "-r"
          - "."
        additional_dependencies: ['toml']
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black-jupyter
        language_version: python3.11